[project]
name = "nlp100"
version = "0.1.0"
description = "NLP100"
readme = "README.md"
requires-python = ">=3.11.12"
dependencies = [
    "gensim>=4.3.3",
    "ginza>=5.2.0",
    "ja-ginza>=5.2.0",
    "matplotlib>=3.10.3",
    "mecab-python3>=1.0.10",
    "numpy>=1.20.0,<2.0.0",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
    "torch>=2.7.1",
    "torchmetrics>=1.8.0",
    "transformers>=4.54.1",
    "unidic-lite>=1.0.8",
]

[project.optional-dependencies]
dev = [
    "pre-commit>=4.2.0",
    "ruff>=0.11.8",
]

[tool.ruff]
target-version = "py311"
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "W", "B", "I"]
ignore = []
fixable = ["ALL"]

[tool.ruff.lint.mccabe]
max-complexity = 5

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
